services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-leovidros
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - leovidros-network

networks:
  leovidros-network:
    driver: bridge