server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT:3000}
  error:
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  forward-headers-strategy: framework

spring:
  application:
    name: extension-project-api
  profiles:
    active: ${APP_ENV:development}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:leo_vidros}
    password: ${RABBITMQ_PASS:leo_vidros_pass}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-retries: 3
        default-requeue-rejected: false
  web:
    error:
      include-message: never

jwt:
  secret: ${JWT_SECRET:minha_chave_secreta_padrao_para_dev_123}

aws:
  region: ${AWS_REGION:us-east-1}
  access-key-id: ${aws_access_key_id:}
  secret-access-key: ${aws_secret_access_key:}
  session-token: ${aws_session_token:}
  s3:
    bucket: ${AWS_S3_BUCKET:}

convertapi:
  key: ${CONVERTAPI_KEY:}

app:
  environment: ${APP_ENV:development}
  orcamento:
    diretorio: ${PDF_STORAGE_PATH:/tmp/orcamentos}
    template-path: "classpath:templates/orcamento.docx"