server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT:3000}
  error:
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  forward-headers-strategy: framework

spring:
  application:
    name: extension-project-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:leo_vidros}
    password: ${RABBITMQ_PASS:leo_vidros_pass}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-retries: 3
        default-requeue-rejected: false
  web:
    error:
      include-message: never

jwt:
  secret: ${JWT_SECRET:minha_chave_secreta_padrao_para_dev_123}

app:
  environment: ${SPRING_PROFILES_ACTIVE:development}
  orcamento:
    diretorio: ${PDF_STORAGE_PATH:/tmp/orcamentos}
    template-path: "classpath:templates/orcamento.docx"