name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build JAR
        working-directory: ./microservice
        run: ./mvnw clean package -DskipTests
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: ./microservice
        run: |
          docker build \
            --no-cache \
            --pull \
            -f Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/leo-vidros-budget-microservice:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/leo-vidros-budget-microservice:$VERSION \
            .
      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/leo-vidros-budget-microservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/leo-vidros-budget-microservice:$VERSION